### ISSUE TITLE
git 2.7 version workaround

### ISSUE THREAD

**Issue by pale3** [lierdakil/vcsh-modules#5]
Hello, 
In latest git version, git doesn't anymore uses git-submodules sh script, instead it is wrapper 
for git-submodule--helper which is written in c.

As a workaround I added 

``` bash
cat $GITMODULES > ./gitmodules
"$GIT_EXEC_PATH_ORIG/git-submodule" "$@"
rm -rf .gitmodules`
```

which recreate .gitmodules on submodule subcommand with entries from 
`.gitmodules.d/repo`

Do you have any better suloution for this?

**Comment by lierdakil** [comment]
https://github.com/lierdakil/vcsh-modules/commit/21862ba39e968b2afd7f86b2ac5c77db544d6094

TL;DR: LD_PRELOAD. You need gcc.

**Comment by pale3** [comment]
ooh, I dont need to tell you that this is not problem (gcc) ;), I will debug it more when time allows, this is just a workaround for me..

**Comment by pale3** [comment]
When i tried to clone my repo, which has in it `gitmodules.d/repo`, and git submodules are registered, i get:

`No url found for submodule path '.location/of/submodule/dir' in .gitmodules`

LD_PRELOAD library is loaded correctly, but it doesnt do nothing. You can test this by 
commenting export LD_PRELOAD, export VCSH_GITMODULES and see yourself. With or without LD_PRELOAD result is the same (msg above^).

Thats the reason why I am redirecting content of gitmodules.d/repo to .gitmodules and destroying it afterwards. 

On what git version you are working on currently?

**Comment by pale3** [comment]
LD_PRELOAD is needed I was wrong. Nice job! 
To fix my issue I revert back 

``` bash
eval "$(cat "$GIT_EXEC_PATH_ORIG/git-submodule" | sed 's/\.gitmodules/"$GITMODULES"/g')"
```

cos in git-submodule script `git config -f .gitmodules` is hardcoded, eval with sed is perfect solution here for variable substitution. With that evertithing is as it should be, thx for this hack.. 

Just wondering which git version you are using, as it seems that you dont need eval at all?

**Comment by lierdakil** [comment]
Okay, I didn't test cloning, so it might be possible this is an issue. But I think LD_PRELOAD should work for bash as well.

**Comment by lierdakil** [comment]
Okay. I have no idea why `git config` doesn't pick up `LD_PRELOAD`. It seems, looking at sources, that it uses pretty much plain old `open` there, but it just refuses.

Anyway, I applied pretty much your change (except unnecessary call to `cat`) to `master`. Thanks!
