### ISSUE TITLE
Can't add a submodule

### ISSUE THREAD

**Issue by antgel** [lierdakil/vcsh-modules#6]
Hi, hope this is the right place to get support. I'm new to vcsh and like many, I guess I failed at the .vim/bundle stage, then I found this project. I've installed the submodule and the config and gitmodules.d are present and correct, but I can't add vundle - see below. Any clues?

```
antony@linuxftw:~$ vcsh dotfiles-vcsh submodule add https://github.com/gmarik/vundle.git ~/.vim/bundle/Vundle.vim                                              
fatal: Could not chdir to '../../../../../../../../../../home/antony/.vim/bundle/Vundle.vim': No such file or directory
Unable to checkout submodule '/home/antony/.vim/bundle/Vundle.vim'
```

**Comment by lierdakil** [comment]
Try `mkdir -p /home/antony/.vim/bundle`, maybe that's that.

**Comment by lierdakil** [comment]
No, sorry, apparently it's not that.

**Comment by lierdakil** [comment]
Okay, I see the problem now. It seems like submodules work only with paths relative to git work dir, at least with vcsh. So you need to specify path _relative to $HOME_, i.e. drop `~/` from path specification:

```
$ vcsh dotfiles-vcsh submodule add https://github.com/gmarik/vundle.git .vim/bundle/Vundle.vim
```
