### ISSUE TITLE
vcsh using .gitmodules instead of .gitmodules.d

### ISSUE THREAD

**Issue by andreas-h** [lierdakil/vcsh-modules#7]
I'm on git 2.14.2 on Arch Linux, vcsh HEAD.

Even though I installed vcsh-modules (and that works, as I can see that the hook.so is being compiled upon first usage), whenever i `vcsh repo submodule add ...`, afterwards I have a `~/.gitmodules` file, and no `~/.gitmodules.d/repo`. However, I don't get any error messages or the like. But still, having a global `~/.gitmodules` for all vcsh repos together is not what we want.

Not sure what changed -- maybe hook.c needs to be adapted for newer git versions?

**Comment by andreas-h** [comment]
When I run `vcsh awesome submodule add https://github.com/copycat-killer/lain.git .config/awesome/lain`, I get

    error: short read: No such file or directory
    error: .gitmodules: failed to insert into database
    error: unable to index file .gitmodules
    fatal: adding files failed
    Failed to register submodule '.config/awesome/lain'

**Comment by andreas-h** [comment]
Sorry the confusion; I believe the case of *lain* is a special one, because the lain repo itself has a submodule again. In that case what I actually end up with is a `~/.gitmodules` file with both lain and lain's submodule in it, **and** `~/.gitmodules.d/awesome`, which only has the lain submodule (but not lain itself).

When I try a simpler case,

    vcsh emacs submodule add https://github.com/jkitchin/ox-ipynb.git .emacs.d/external/ox-ipynb

then I only get a new entry in `~/.gitmodules`, but no `~/.gitmodules.d/emacs`.

**Comment by lierdakil** [comment]
Well, git changed how they handle this stuff *again*, so either I hook into half the POSIX API, or find another way... sigh... maybe it's about time I tried patching git directly, i.e. by submitting a pull request.

**Comment by lierdakil** [comment]
If you're comfortable checking out a branch, `symlink-substituiton` should hopefully work with newer git releases. It's even more hacky, but hopefully backwards-compatible with earlier git versions. If you could confirm that it works for you, that'd be nice.

**Comment by lierdakil** [comment]
Better yet, `eval-injection-new` branch might work as well, and is, in some sense, less hacky.

**Comment by andreas-h** [comment]
Thanks, that's great!!  I believe your changes (eval-injection-new branch) are a partial success:

    $ vcsh test123 submodule add https://github.com/copycat-killer/lain.git testsubmodule
    Cloning into '/home/andreash/testsubmodule'...
    remote: Counting objects: 5595, done.
    remote: Total 5595 (delta 0), reused 0 (delta 0), pack-reused 5595
    Receiving objects: 100% (5595/5595), 1.33 MiB | 2.15 MiB/s, done.
    Resolving deltas: 100% (3389/3389), done.
    
    $ ls .gitmodules
    ls: cannot access '.gitmodules': No such file or directory
    
    $ ls .gitmodules.d/test123 
    .gitmodules.d/test123
    
    $ cat .gitmodules.d/test123 
    [submodule "testsubmodule"]
    	path = testsubmodule
    	url = https://github.com/copycat-killer/lain.git
    
    $ vcsh test123 submodule init
    fatal: No url found for submodule path 'testsubmodule' in .gitmodules
    
    $ vcsh test123 submodule sync
    
    $ vcsh test123 submodule update
    
    $

The only strange thing is the `submodule init` call error.  Unfortunately, I'm not really sure what that means or what to do about it.

**Comment by andreas-h** [comment]
No errors with the symlink-substituiton branch:

    $ vcsh init test234
    Initialized empty shared Git repository in /home/andreash/.config/vcsh/repo.d/test234.git/
    
    $ vcsh test234 submodule add https://github.com/copycat-killer/lain.git testsubmodule2
    Cloning into '/home/andreash/testsubmodule2'...
    remote: Counting objects: 5595, done.
    remote: Total 5595 (delta 0), reused 0 (delta 0), pack-reused 5595
    Receiving objects: 100% (5595/5595), 1.33 MiB | 2.19 MiB/s, done.
    Resolving deltas: 100% (3389/3389), done.
    
    $ ls .gitmodules
    ls: cannot access '.gitmodules': No such file or directory
    
    $ ls .gitmodules.d/
    awesome  bla  emacs  test123  test234
    
    $ cat .gitmodules.d/test234 
    [submodule "testsubmodule2"]
    	path = testsubmodule2
    	url = https://github.com/copycat-killer/lain.git
    
    $ vcsh test234 submodule init
    
    $ vcsh test234 submodule sync
    Synchronizing submodule url for 'testsubmodule2'
    
    $ vcsh test234 submodule update
    
    $

**Comment by lierdakil** [comment]
Right. That's probably because `init` uses a binary helper, and I missed that (it was 4 am and I was sleepy).
