### ISSUE TITLE
Maybe git-submodule is broken?

### ISSUE THREAD

**Issue by tyrion** [lierdakil/vcsh-modules#9]
If I try to add a submodule, or even just run `vcsh anyrepo submodule` I get:

```
fatal: 'submodule' appears to be a git command, but we were not
able to execute it. Maybe git-submodule is broken?
```

Any idea how to debug this?

**Comment by lierdakil** [comment]
Hm. Kinda weird. If you're on `master` branch (which you are if unsure), then the first thing I'd check is whether `$HOME/.config/vcsh/gitmodules/git-submodule` is executable and isn't corrupted. Also, it expects to find `bash` in `/bin/bash`

**Comment by tyrion** [comment]
Thanks, the problem was the hardcoded `/bin/bash`!
I am using nixos and stuff here is in non-standard places. The only thing that is in `/usr/bin` in nixos is `env`, to allow shebangs to work.

Would you consider changing the shebang to `#!/usr/bin/env bash`?

**Comment by lierdakil** [comment]
Argh, sorry, I forgot about this. Made the change.

**Comment by tyrion** [comment]
No worries. Thank you for the change :)
